[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
name = "f3"
version = "0.1.0"

[dependencies]
cortex-m = { git = "https://github.com/japaric/cortex-m" }
embedded-hal = { git = "https://github.com/japaric/embedded-hal", branch = "v1" }
l3gd20 = { git = "https://github.com/japaric/l3gd20" }
nb = { git = "https://github.com/japaric/nb" }
stm32f30x = { git = "https://github.com/japaric/stm32f30x" }

[dev-dependencies]
cortex-m-rt = { version = "0.3.9", features = ["abort-on-panic"] }
stm32f30x = { git = "https://github.com/japaric/stm32f30x", features = ["rt"] }

[profile.dev]
incremental = false
codegen-units = 1