[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
name = "f3"
version = "0.1.0"

[dependencies]
l3gd20 = { git = "https://github.com/japaric/l3gd20" }
lsm303dlhc = { git = "https://github.com/japaric/lsm303dlhc" }
stm32f30x-hal = { git = "https://github.com/japaric/stm32f30x-hal" }

[dev-dependencies]
cortex-m = { git = "https://github.com/japaric/cortex-m" }
cortex-m-rt = { version = "0.3.9", features = ["abort-on-panic"] }
nb = "0.1.1"
stm32f30x = { git = "https://github.com/japaric/stm32f30x", features = ["rt"] }

[profile.dev]
codegen-units = 1

[profile.release]
debug = true
lto = true